gitlab: exit with error code when manifests fail to validate
The generate-manifests jobs in gitlab CI are meant to catch invalid
manifest generation for the two architectures we don't build test:
ppc64le and s390x.  The way the test is written however, errors are
printed but do not cause the execution to fail.

Fix the test script to exit with an error code.  The exit code is the
number of manifests that failed to validate.

diff --git a/test/scripts/generate-gitlab-ci b/test/scripts/generate-gitlab-ci
--- a/test/scripts/generate-gitlab-ci
+++ b/test/scripts/generate-gitlab-ci
@@ -120,18 +120,22 @@ MANIFEST_GEN_TEMPLATE = """
   variables:
     RUNNER: {runner}-x86_64
     INTERNAL_NETWORK: "true"
-  script:
-    - sudo ./test/scripts/setup-osbuild-repo
-    - sudo ./test/scripts/install-dependencies
-    - echo "GOPROXY=$GOPROXY"
-    - go run ./cmd/gen-manifests --arches {arch} --distros {distro} --workers 10 --metadata=false --output ./manifests
-    - for manifest in ./manifests/*; do
-        if osbuild --inspect $manifest > output; then
-          echo "$manifest OK";
-        else
-          cat output;
-        fi;
-      done
+  script: |
+    sudo ./test/scripts/setup-osbuild-repo
+    sudo ./test/scripts/install-dependencies
+    echo "GOPROXY=$GOPROXY"
+    go run ./cmd/gen-manifests --arches {arch} --distros {distro} --workers 10 --metadata=false --output ./manifests
+    errors=0
+    for manifest in ./manifests/*; do
+      if osbuild --inspect $manifest > output; then
+        echo "$manifest OK";
+      else
+        echo "$manifest validation failed";
+        cat output;
+        errors+=1
+      fi;
+    done
+    exit "$errors"
 """
 
 
